#!/usr/bin/env python3
"""
Analyze the default Rubiks4D keybinds to find the simplest move execution
"""

print("Default Rubiks4D Keybinds Analysis")
print("=" * 60)
print()
print("From ~/.config/hyperspeedcube/hyperspeedcube.yaml:")
print()
print("BASIC TWISTS (always available):")
print("  I  → twist in +x direction (layer 1)")
print("  K  → twist in -x direction (layer 1)")
print("  J  → twist in +y direction (layer 1)")
print("  L  → twist in -y direction (layer 1)")
print("  U  → twist in -z direction (layer 1)")
print("  O  → twist in +z direction (layer 1)")
print()
print("These twists apply to the CURRENTLY GRIPPED axis.")
print("If no axis is gripped, they affect the Inside (I) cell.")
print()
print("GRIP SYSTEM (from keybinds.png):")
print("  W → grip L (Left)")
print("  E → grip U (Up)")
print("  R → grip B (Back)")
print("  S → grip F (Front)")
print("  D → grip I (Inside)")
print("  F → grip R (Right)")
print("  C → grip D (Down)")
print("  V → grip O (Outside)")
print()
print("SIMPLEST MOVE EXECUTION:")
print("  1. Press grip key (hold)")
print("  2. Press twist direction key")
print("  3. Release grip key")
print()
print("For our moves:")
print("  FR = Hold S (Front), press I or K (x direction)")
print("  FO = Hold S (Front), press U or O (z direction toward Outside)")
print()
print("=" * 60)
print()
print("Recommendation: Use the grip+twist system")
print("  FR: Hold 's', press 'i'")
print("  FO: Hold 's', press 'o'")
print()
